let animals = [
    "bulbasaur",
    "pikachu",
    "mewtwo",
    "mew",
    "ivysaur",
    "dragonair",
    "dratini",
    "dragonite",
    "charmeleon",
    "squirtle",
    "blastoise",
    "caterpie",
    "butterfree",
    "metapod",
    "kakuna",
    "beedrill",
    "clefairy",
    "arbok",
    "sandslash",
    "nidorina",
    "nidoqueen",
    "clefable",
    "vulpix",
    "jigglypuff",
    "oddish",
    "gloom",
    "vileplume",
    "parasect",
    "venonat",
    "diglett",
    "dugtrio",
    "persian",
    "psyduck",
    "golduck",
    "mankey",
    "primeape",
    "growlithe",
    "arcanine",
    "poliwag",
    "poliwhirl",
    "poliwrath",
    "abra",
    "kadabra",
    "alakazam",
    "bellsprout",
    "weepinbell",
    "tentacruel",
    "geodude",
    "graveler",
    "ponyta",
    "magnemite",
    "magneton",
    "doduo",
    "dodrio",
    "dewgong",
    "haunter",
    "hypno",
    "kingler",
    "voltorb",
    "electrode",
    "cubone",
    "marowak",
    "hitmonlee",
    "hitmonchan",
    "lickitung",
    "tangela",
    "kangaskhan",
    "seadra",
    "goldeen",
    "scyther",
    "electabuzz",
    "magmar",
    "tauros",
    "magikarp",
    "ditto",
    "lapras",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "kabuto",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "articuno",
    "moltres"
];

let animalSprites = {
    bulbasaur: {},
    pikachu: {},
    mewtwo: {},
    mew: {},
    ivysaur: {},
    dragonair: {},
    dratini: {},
    dragonite: {},
    charmeleon: {},
    squirtle: {},
    blastoise: {},
    caterpie: {},
    butterfree: {},
    metapod: {},
    kakuna: {},
    beedrill: {},
    clefairy: {},
    arbok: {},
    sandslash: {},
    nidorina: {},
    nidoqueen: {},
    clefable: {},
    vulpix: {},
    jigglypuff: {},
    oddish: {},
    gloom: {},
    vileplume: {},
    parasect: {},
    venonat: {},
    diglett: {},
    dugtrio: {},
    persian: {},
    psyduck: {},
    golduck: {},
    mankey: {},
    primeape: {},
    growlithe: {},
    arcanine: {},
    poliwag: {},
    poliwhirl: {},
    poliwrath: {},
    abra: {},
    kadabra: {},
    alakazam: {},
    bellsprout: {},
    weepinbell: {},
    tentacruel: {},
    geodude: {},
    graveler: {},
    ponyta: {},
    magnemite: {},
    magneton: {},
    doduo: {},
    dodrio: {},
    dewgong: {},
    haunter: {},
    hypno: {},
    kingler: {},
    voltorb: {},
    electrode: {},
    cubone: {},
    marowak: {},
    hitmonlee: {},
    hitmonchan: {},
    lickitung: {},
    tangela: {},
    kangaskhan: {},
    seadra: {},
    goldeen: {},
    scyther: {},
    electabuzz: {},
    magmar: {},
    tauros: {},
    magikarp: {},
    ditto: {},
    lapras: {},
    vaporeon: {},
    jolteon: {},
    flareon: {},
    porygon: {},
    kabuto: {},
    kabutops: {},
    aerodactyl: {},
    snorlax: {},
    articuno: {},
    moltres: {}
};